In [3]:
import pandas as pd

# Reading the required dataset

In [4]:
dataset = pd.read_csv("winequality-red.csv")

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
fixed acidity           1599 non-null float64
volatile acidity        1599 non-null float64
citric acid             1599 non-null float64
residual sugar          1599 non-null float64
chlorides               1599 non-null float64
free sulfur dioxide     1599 non-null float64
total sulfur dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

# Preparing Data for Classification 

In [7]:
quality = dataset["quality"].values
category = []
for num in quality:
    if num<=6:
        category.append("Bad")
    else :
        category.append("Good")
   

In [8]:
category = pd.DataFrame(data=category, columns=["Quality_class"])

In [9]:
dataset1 = pd.concat([dataset,category],axis=1)
dataset1.drop(columns="quality",axis=1,inplace=True)

In [10]:
dataset1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol Quality_class  
0         9.4           Bad  
1         9.8           Bad  
2         9.8           Bad  
3         9.8           Bad  
4         9.4           Bad  
...       ...           ...  
1594     10.5           Bad  
1595     11.2           Bad  
1596     11.0           Bad  
1597     10.2           Bad  
1598     11.0           Bad  

[1599 rows x 12 columns]

In [11]:
X= dataset1.iloc[:,:-1].values
y=dataset1.iloc[:,-1].values

In [12]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
y= le.fit_transform(y)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Importing and Applying Different Classification Algorithms

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [16]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [17]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [18]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

# Confusion Matrices For each Algorithms 

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [21]:
l_c

array([[277,  13],
       [ 18,  12]], dtype=int64)

In [22]:
k_c

array([[276,  14],
       [ 13,  17]], dtype=int64)

In [23]:
d_c

array([[265,  25],
       [  8,  22]], dtype=int64)

In [24]:
r_c

array([[281,   9],
       [ 15,  15]], dtype=int64)

In [25]:
s_c

array([[290,   0],
       [ 30,   0]], dtype=int64)

In [26]:
ks_c

array([[285,   5],
       [ 21,   9]], dtype=int64)

# Accuracy Score Of the algorithms 

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [29]:
print('Logistic Regression: ' + str(l_a) + '\nKNN : ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.903125
KNN : 0.915625
Decision Tree: 0.896875
Random Forest: 0.925
Linear SVC: 0.90625
Kernel SVC: 0.903125


# Preparing Data for Regression 

In [30]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [31]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.preprocessing import StandardScaler
t_train = y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)
X_sc = StandardScaler()
y_sc = StandardScaler()


In [33]:
X_std_train = X_sc.fit_transform(X_train)
y_std_train = y_sc.fit_transform(t_train)

In [34]:
X_std_test = X_sc.transform(X_test)
y_std_test = y_sc.transform(t_test)

# Importing and Applying Different Regression Algorithms 

In [46]:
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [47]:
m_reg=LinearRegression()
p_reg=LinearRegression()
d_reg=DecisionTreeRegressor()
r_reg=RandomForestRegressor()
s_reg=SVR()

In [48]:
X_poly = PolynomialFeatures(degree=2)
X_poly = X_poly.fit_transform(X_train)

In [49]:
m_reg.fit(X_train,y_train)
p_reg.fit(X_poly,y_train)
r_reg.fit(X_train,y_train)
d_reg.fit(X_train,y_train)
s_reg.fit(X_std_train,y_std_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [50]:
temp = PolynomialFeatures(degree =2)
temp = temp.fit_transform(X_test)

In [51]:
m_pred=m_reg.predict(X_test)
p_pred=p_reg.predict(temp)
r_pred=r_reg.predict(X_test)
d_pred=d_reg.predict(X_test)
s_pred=s_reg.predict(X_std_test)

# Finding the R^2 score 

In [52]:
from sklearn.metrics import r2_score

In [53]:
m= r2_score(y_test,m_pred)
p= r2_score(y_test,p_pred)
r= r2_score(y_test,r_pred)
d= r2_score(y_test,d_pred)
s= r2_score(y_std_test,s_pred)

In [54]:
print('Linear Regression: ' + str(m) + '\nPolynomial Regression. : ' + str(p) + '\nDecision Tree: ' + str(d) + '\nRandom Forest: ' + str(r) + '\nSupport Vector Regression SVC: ' + str(s) )

Linear Regression: 0.33030859178924343
Polynomial Regression. : 0.302950754567889
Decision Tree: -0.010438541363295029
Random Forest: 0.3925106148162909
Support Vector Regression SVC: 0.39704028841341166


# Conclusion  